### ISSUE TITLE
[Question] I want to add Unity 2017.2.1p3

### ISSUE THREAD

**Issue by boskiv** [wooga/homebrew-unityversions#2]
I want to add Unity 2017.2.1p3. I have found version after coma, 
but I cant found sha checksums for packages. Where you get it ?

**Comment by boskiv** [comment]
Can you share it ?

**Comment by boskiv** [comment]
I can do some pull requests

**Comment by Larusso** [comment]
let me check. The project is closed source and I don't remember anymore why :)

**Comment by boskiv** [comment]
May be some license restrictions from Unity ? :)

**Comment by boskiv** [comment]
Ok, I see 2017.2.1p4 how about to get 2017.2.1p3 ?

**Comment by Larusso** [comment]
I already triggered a build.

**Comment by boskiv** [comment]
Can you tell a login of getting sha256 sums ? Did you download package and make sum yourself ?

**Comment by Larusso** [comment]
I pre-fetch them and calculate the sum and then cache it.

**Comment by boskiv** [comment]
Ok, got it. thanks.

**Comment by Larusso** [comment]
FYI https://github.com/wooga/homebrew-unityversions/tree/6bf569ddd2640d670dd7904e375258bafb5407b7 this commit contains the old Rake script to generate the casks. It should still work. I moved to gradle because most build scripts I support today are written in it.
